ui-ux : improved api-key-manager component
stackblitz-labs/bolt.diy pull request #732
Opened 2024-12-15 08:36 UTC by Adithyan777

- Modified the API Key Manager to show users whether the API key is set via environment variables or the UI.
- Implemented an API route to check and report the API key status dynamically based on the model provider.
-  The API key set via the UI is reset when the user switches to a different model provider

![Screenshot 2024-12-15 at 1 53 33 PM](https://github.com/user-attachments/assets/c9154f2a-626a-4a54-b3de-a126b5e2b2ec)
![Screenshot 2024-12-15 at 1 53 55 PM](https://github.com/user-attachments/assets/182e9207-8068-4f39-8e58-f89e44864b6b)
![Screenshot 2024-12-15 at 1 58 30 PM](https://github.com/user-attachments/assets/ed8778eb-f25f-4090-85e2-5b5d553d0ff6)
![Screenshot 2024-12-15 at 2 03 29 PM](https://github.com/user-attachments/assets/961174cb-9ed7-4657-a6eb-0fc43154b645)

2024-12-19 06:38 UTC, kalyanipujari204 commented
bro can you tell me step by step how to run this project on vs code

2024-12-19 16:18 UTC, thecodacus requested changes
This is a great implementation, it keeps the keys safe and gives feedback.
I have added some comments please check those, after that its good to merge

2024-12-30 19:01 UTC, thecodacus commented
hi @Adithyan777, I want to merge this for the next release, will you be addressing the changes I have mentioned in the review, so that i can queue up this for next release?

2024-12-31 11:26 UTC, thecodacus commented
sure, thanks for the update

2025-01-04 20:18 UTC, Adithyan777 commented
hi @thecodacus, I've addressed most of the requested changes from the review. However, for the suggestion to import the map from utils/constants file , I couldn't locate it. Could you confirm if it's defined elsewhere, or provide more details on where I can find it?

2025-01-05 12:01 UTC, thecodacus commented
Hi, thanks for the update,
you can check this variable  from constants which has map of all the env keys names

![image](https://github.com/user-attachments/assets/27c4d5ff-7456-4007-863e-9112d1412817)

2025-01-06 07:35 UTC, Adithyan777 commented
hi @thecodacus , I've addressed all the requested changes. Let me know if there's anything else to change.

2025-01-06 12:39 UTC, thecodacus commented on app/components/chat/BaseChat.tsx
>          } catch (error) {
is this section really required?, we are already saving the keys in the above line.

and anytime any apikey changes `onApiKeysChange ` is called anyway from below 
```typescript
<APIKeyManager
  provider={provider}
  apiKey={apiKeys[provider.name] || ''}
  setApiKey={(key) => {
    onApiKeysChange(provider.name, key);
  }}
/>
```

the key is stores as an object so does not matter if the provider changed, during api call it pulls the correct apiKey from the object for that provider

2025-01-06 12:40 UTC, thecodacus commented
> hi @thecodacus , I've addressed all the requested changes. Let me know if there's anything else to change.

everything looks good except the apikey set on provider change might be redundant block. 
I have added comment.
once this addressed I can merge this

2025-01-10 15:56 UTC, merged